/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import doc. doctor;
import javax.swing.JOptionPane;
import oop_project.*;

/**
 *
 * @author DELL
 */
public class View_Patient extends javax.swing.JFrame {

    /**
     * Creates new form View_Patient
     */
   
    public View_Patient() {
        initComponents();
        this.setSize(950,750);
         t1.setEditable(false);
          t4.setEditable(false);
           t2.setEditable(false);
            t5.setEditable(false);
             t3.setEditable(false);
              t6.setEditable(false);
       // text2.setEnabled(false);
      
    }
    
    
    doctor p=new doctor();
    
    
    static String s11, s22 , s33 , s44,s55;
          
  
    static  int s66;
   
   
    
      static void ve(String s1,String s2,String s3,String s4,String s5,int s6){
      
     s11=s1;// name gender age add phone token
     s22=s2;
     s33=s3;
     s44=s4;
     s55=s4;
     s66=s6;
           
  
      }
  
    
    
    
    
    
    
    
    
    
    
    
    
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 128, 128));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 128, 128));
        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Patient Id: ");

        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jButton1)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-10, 0, 950, 80);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 128, 128));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(700, 240, 90, 39);

        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel3.add(t1);
        t1.setBounds(260, 60, 160, 28);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 128, 128));
        jLabel4.setText("name");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(190, 60, 70, 30);

        t6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel3.add(t6);
        t6.setBounds(260, 120, 160, 28);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 128, 128));
        jLabel9.setText("Token Number");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(100, 120, 150, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 128, 128));
        jLabel8.setText("age");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(170, 170, 60, 30);

        t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel3.add(t3);
        t3.setBounds(260, 170, 160, 28);

        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel3.add(t2);
        t2.setBounds(560, 60, 160, 28);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 128, 128));
        jLabel6.setText("gender");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(480, 60, 90, 30);

        t4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel3.add(t4);
        t4.setBounds(560, 120, 160, 28);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 128, 128));
        jLabel5.setText("address");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(470, 120, 90, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 128, 128));
        jLabel7.setText("phone");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(470, 170, 80, 30);

        t5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel3.add(t5);
        t5.setBounds(560, 170, 160, 28);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(-10, 80, 950, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

    }//GEN-LAST:event_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Add_patient d = new Add_patient();
        d.search(search.getText());
        // name gender age add phone token
        t1.setText(s11);
        t2.setText(s22);
        t3.setText(s33);
        t4.setText(s44);
        t5.setText(s55);
        String s666=String.valueOf(s66);

        t6.setText(s666);

        if( t1.getText() .equals(" ") ){

            JOptionPane.showMessageDialog(null,  "you deleted this patient ",  "TITLE",  JOptionPane.WARNING_MESSAGE);

        }

        // if (search.getText().equals())
        boolean bb= Add_patient.wrongId((search.getText()));

        if(bb==false)

        JOptionPane.showMessageDialog(null,  "not found ",  "TITLE",  JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Home_page Sign= new Home_page();
        if(Sign.cheak==1){
            Receptionist r= new Receptionist();
            this.dispose();
            r.setVisible(true);
        }
        else if(Sign.cheak==2){
            Page_Admin admin = new Page_Admin();
            this.dispose();
            admin.setVisible(true);
        }
        else if(Sign.cheak==3){
            doctor doc=new doctor();
            this.dispose();
            doc.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
      static void set(String s1,String s2,String s3,String s4 ){
          
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        View_Patient v=new  View_Patient();
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField search;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
