package doc;


import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.print.PrinterIOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.print.PrinterException;
import javax.swing.JTextField;
import oop_project.Home_page;
import project.Add_patient;
import project.Receptionist;
import oop_project.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package add_prescription;

/**
 *
 * @author mariam
 */
public class addPrescrip1 extends search_users {
public static String s;
 
private JFrame frame;
    /**
     * Creates new form addPrescrip
     */
    public addPrescrip1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtnum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtdose = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtuse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jtxtexp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtref = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtprescreption = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jtxtid.setToolTipText("");
        jtxtid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel1.add(jtxtid);
        jtxtid.setBounds(530, 120, 160, 28);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 128, 128));
        jLabel8.setText("Patient Id");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(390, 120, 140, 30);

        jtxtnum.setToolTipText("");
        jtxtnum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel1.add(jtxtnum);
        jtxtnum.setBounds(200, 420, 160, 28);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 128, 128));
        jLabel6.setText("Num of Tablets");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 430, 160, 30);

        jtxtdose.setToolTipText("");
        jtxtdose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel1.add(jtxtdose);
        jtxtdose.setBounds(200, 360, 160, 28);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 128, 128));
        jLabel5.setText("Dailly Dose");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 370, 120, 30);

        jtxtuse.setToolTipText("");
        jtxtuse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel1.add(jtxtuse);
        jtxtuse.setBounds(200, 300, 160, 28);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 128, 128));
        jLabel4.setText("How to Use");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 300, 130, 30);

        jButton3.setBackground(new java.awt.Color(0, 128, 128));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Prescription");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(270, 540, 160, 40);

        jButton4.setBackground(new java.awt.Color(0, 128, 128));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(440, 540, 120, 40);

        jButton1.setBackground(new java.awt.Color(0, 128, 128));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(570, 540, 110, 39);

        jtxtexp.setToolTipText("");
        jtxtexp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel1.add(jtxtexp);
        jtxtexp.setBounds(200, 230, 160, 28);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 128, 128));
        jLabel2.setText("Exp Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 230, 100, 30);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 128, 128));
        jLabel1.setText("Referance NO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 170, 150, 30);

        jtxtref.setToolTipText("");
        jtxtref.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel1.add(jtxtref);
        jtxtref.setBounds(200, 170, 160, 28);

        jComboBox1.setBackground(new java.awt.Color(0, 128, 128));
        jComboBox1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Make a selection", "Ibuprofen", "Pandol", "Paracetemol", "Amiodipine", "Cataflam", "Catafast", "Flagyl", "Congestal", "Aspirin", "Atenolol", "Atropine", "", "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(200, 110, 160, 29);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 128, 128));
        jLabel3.setText("Name of Tablets");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 110, 170, 30);

        jPanel4.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(730, 120, 20, 470);

        jPanel7.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(730, 590, 590, 20);

        jtxtprescreption.setColumns(20);
        jtxtprescreption.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jtxtprescreption.setForeground(new java.awt.Color(0, 128, 128));
        jtxtprescreption.setRows(5);
        jScrollPane1.setViewportView(jtxtprescreption);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(750, 120, 550, 470);

        jPanel6.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(730, 100, 590, 20);

        jPanel5.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(1300, 120, 20, 470);

        jPanel3.setBackground(new java.awt.Color(0, 128, 128));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ADD Prescription");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10)
                .addContainerGap(968, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1340, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1340, 710);

        setSize(new java.awt.Dimension(1338, 716));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
               
        if (jComboBox1.getSelectedItem().equals("Ibuprofen") )
       {
     
    
         jtxtref.setText("ibu1212");
       jtxtdose.setText("3");
       jtxtnum.setText("30");
       jtxtexp.setText("5/6/2028");
       jtxtuse.setText("Use water to drink it");
       
       
       }
        
       else if(jComboBox1.getSelectedItem().equals("Pandol"))
       {
       
         jtxtref.setText("pan1212");
       jtxtdose.setText("3");
       jtxtnum.setText("40");
       jtxtexp.setText("5/6/2021");
       jtxtuse.setText("Use water to drink it");
       
       
       }
        else if(jComboBox1.getSelectedItem().equals("Paracetemol"))
       {
       
         jtxtref.setText("par1212");
       jtxtdose.setText("4");
       jtxtnum.setText("32");
       jtxtexp.setText("5/6/2025");
       jtxtuse.setText("Use water to drink it");
       
       
       }
        else if(jComboBox1.getSelectedItem().equals("Amiodipine"))
       {
       
         jtxtref.setText("ami1212");
       jtxtdose.setText("3");
       jtxtnum.setText("45");
       jtxtexp.setText("5/6/2029");
       jtxtuse.setText("Use water to drink it");
       
       
       }
        else if(jComboBox1.getSelectedItem().equals("Cataflam"))
       {
       
         jtxtref.setText("cat1212");
       jtxtdose.setText("3");
       jtxtnum.setText("20");
       jtxtexp.setText("5/6/2028");
       jtxtuse.setText("Use water to drink it");
       
       
       }
        else if(jComboBox1.getSelectedItem().equals("Flygl"))
       {
       
         jtxtref.setText("fly1212");
       jtxtdose.setText("3");
       jtxtnum.setText("24");
       jtxtexp.setText("5/6/2024");
       jtxtuse.setText("Use water to drink it");
       
       
       }
        else if(jComboBox1.getSelectedItem().equals("Aspirin"))
       {
       
         jtxtref.setText("asp1212");
       jtxtdose.setText("3");
       jtxtnum.setText("40");
       jtxtexp.setText("5/6/2021");
       jtxtuse.setText("Use water to drink it");
       
       
       }
        else if(jComboBox1.getSelectedItem().equals("Atenolol"))
       {
       
         jtxtref.setText("ate1212");
       jtxtdose.setText("3");
       jtxtnum.setText("40");
       jtxtexp.setText("5/6/2021");
       jtxtuse.setText("Use water to drink it");
       
       
       }
        else if(jComboBox1.getSelectedItem().equals("Atropine"))
       {
       
         jtxtref.setText("atr1212");
       jtxtdose.setText("3");
       jtxtnum.setText("40");
       jtxtexp.setText("5/6/2021");
       jtxtuse.setText("Use water to drink it");
       
       
       }
            else if(jComboBox1.getSelectedItem().equals("Catafast"))
       {
       
         jtxtref.setText("atr1212");
       jtxtdose.setText("3");
       jtxtnum.setText("40");
       jtxtexp.setText("5/6/2021");
       jtxtuse.setText("Use water to drink it");
       
       
       }
        else if(jComboBox1.getSelectedItem().equals("Make a selection"))
       {
       
         jtxtref.setText(" ");
       jtxtdose.setText(" ");
       jtxtnum.setText(" ");
       jtxtexp.setText(" ");
       jtxtuse.setText(" ");
       
       
       }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
      jtxtprescreption.print();
       
       }
       catch(PrinterException ex){
       Logger.getLogger(addPrescrip1.class.getName()).log(Level.SEVERE,null,ex);
       
       }
               try {
String msg = dis.readUTF();
String oldText = jtxtprescreption.getText();

StringBuilder yourStringBuilder = new StringBuilder();
yourStringBuilder.append(oldText);
yourStringBuilder.append("\\n");
yourStringBuilder.append(msg);

jtxtprescreption.setText(yourStringBuilder.toString());
} catch (Exception ex) {
Logger.getLogger(addPrescrip1.class.getName()).log(Level.SEVERE, null, ex);
}
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                s= jComboBox1.getSelectedItem().toString();
     

        boolean bbb;
    bbb = Add_patient.wrongId((jtxtid.getText()));
       if(bbb==false){
       
          JOptionPane.showMessageDialog(null,  "not found ",  "TITLE",  JOptionPane.WARNING_MESSAGE);
       }
       else if(bbb==true){
          

        String q1=(jtxtref.getText());
        String q2=(jtxtdose.getText());
        String q3=(jtxtnum.getText());
        String q4=(jtxtexp.getText());
        String q5=(jtxtuse.getText());
      //  String q6=(name.getText());
        String q7=(jtxtid.getText());
        
        String q9=" ";
        
            Add_patient p = new Add_patient();
            p.search(jtxtid.getText());
          String  n= Add_patient.namepa(jtxtid.getText());
       
     
        
       
        
         if (jComboBox1.getSelectedItem().equals("Pandol") )
       {
          q9="Pandol";
       }
      
          
         
            else if (jComboBox1.getSelectedItem().equals("Cataflam") )
       {
          q9="Cataflam";
        
       }
      
          else if (jComboBox1.getSelectedItem().equals("Aspirin") )
       {
          q9="Aspirin";
        
       }
      
           else if (jComboBox1.getSelectedItem().equals("Make a selection") )
       {
          q9="Make a selection";
        
       }
       
          
        jtxtprescreption.setText(" ");
        jtxtprescreption.append("\t\n\tClinc Management System\n"
        +"\nPatient Name:\t\t"+n
          +"\nPatient ID:\t\t"+q7
    
                 +"\nName of Tablets:\t\t"+q9
                 +"\nRefreance NO:\t\t"+q1
                 +"\nHow to use it?:\t\t"+q5
                 +"\nDaily Dose:\t\t"+q2
                +"\nExp date:\t\t"+q4
                +"\nNumber of Tabletes:\t\t"+q3
                
        +"\n\n\tPatient Instruction we have introduced"
               +"-------------------\n\n\t"
                +"TEXT REMINDERS FOR YOUR MEDICINES");
    }                                        
 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home_page H = new Home_page();
        if(H.cheak==3){
        doctor d=new doctor();
        this.dispose();
        d.setVisible(true);
        }
        else if(H.cheak==1){
            Receptionist r= new Receptionist();
            this.dispose();
            r.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addPrescrip1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addPrescrip1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addPrescrip1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addPrescrip1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()*/      
        java.awt.EventQueue.invokeLater(() -> {
 {
                new addPrescrip1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtdose;
    private javax.swing.JTextField jtxtexp;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtnum;
    private javax.swing.JTextArea jtxtprescreption;
    private javax.swing.JTextField jtxtref;
    private javax.swing.JTextField jtxtuse;
    // End of variables declaration//GEN-END:variables
   public static String combo() {
        return s; //To change body of generated methods, choose Tools | Templates.
    }
}
