/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop_project;

import javax.swing.JOptionPane;


/**
 *
 * @author هديل
 */
public class AddDoctor extends search_users {

    /**
     * Creates new form AddDoctor
     */
    public AddDoctor() {
        initComponents();
        this.setSize(950,750);
    }
     static dataForRecep_doc[] doc = new dataForRecep_doc[80];
    static int i = 0;
     void insert_doctor(dataForRecep_doc d) {
        doc[i] = d;      
        i++;
    }
     public void search(String idd){
   for (int j = 0; j < i; j++) {
    if(idd.equals(doc[j].id)){
  
            String na=   doc[j].name;
            String jo = doc[j].jopType;
            String add = doc[j].address; 
            String pho=    doc[j].phone;
            String ag=     doc[j].age;
            String gen=   doc[j].gender;
            String us=     doc[j].username;
            String pass=   doc[j].password;
         
           viewDoctor.vie(na, ag, jo, gen, pho, add, us, pass);
    }
    
   }
     }
         public static  boolean wrongId(String id){
    for(int j=0;j<i;j++){
     if(id.equals(doc[j].id)){
       
       return true;
     }  
     }
      return false;
     }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        job = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 128, 128));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Doctor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addContainerGap(550, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 970, 100);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 128, 128));
        jLabel9.setText("Username");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(500, 60, 110, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 128, 128));
        jLabel10.setText("Password");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(500, 110, 100, 30);

        jButton2.setBackground(new java.awt.Color(0, 128, 128));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(690, 400, 79, 39);

        reset.setBackground(new java.awt.Color(0, 128, 128));
        reset.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset);
        reset.setBounds(540, 400, 110, 41);

        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel2.add(jTextField8);
        jTextField8.setBounds(630, 60, 160, 28);

        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name);
        name.setBounds(280, 60, 160, 28);

        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel2.add(id);
        id.setBounds(280, 110, 160, 28);

        job.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel2.add(job);
        job.setBounds(280, 160, 160, 28);

        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel2.add(add);
        add.setBounds(280, 210, 160, 28);

        phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel2.add(phone);
        phone.setBounds(630, 210, 160, 28);

        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jPanel2.add(age);
        age.setBounds(630, 160, 160, 28);

        jComboBox1.setBackground(new java.awt.Color(0, 128, 128));
        jComboBox1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "male", "female" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(500, 290, 90, 36);

        jButton1.setBackground(new java.awt.Color(0, 128, 128));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Doctor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(350, 400, 150, 41);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 128, 128));
        jLabel2.setText("Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 60, 70, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 128, 128));
        jLabel3.setText("ID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(210, 110, 40, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 128, 128));
        jLabel4.setText("Jop");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 170, 40, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 128, 128));
        jLabel5.setText("Adress");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(190, 210, 80, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 128, 128));
        jLabel7.setText("Age");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(510, 210, 60, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 128, 128));
        jLabel6.setText("Phone");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(510, 160, 80, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 128, 128));
        jLabel8.setText("gender");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(410, 300, 70, 30);

        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 128)));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7);
        jTextField7.setBounds(630, 110, 160, 28);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 970, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Page_Admin admin = new Page_Admin(); 
        this.dispose();
        admin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        //cancle
        name.setText(null);
        id.setText(null);
        job.setText(null);
        add.setText(null);
        phone.setText(null);
        age.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
    }//GEN-LAST:event_resetActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(name.getText().trim().isEmpty()||add.getText().trim().isEmpty()||phone.getText().trim().isEmpty()||age.getText().trim().isEmpty()||job.getText().trim().isEmpty()||jTextField7.getText().trim().isEmpty()||jTextField8.getText().trim().isEmpty()) {
     JOptionPane.showMessageDialog(this,"Text box should not be empty.","Erorr", JOptionPane.ERROR_MESSAGE);           
        }         
        String gen = jComboBox1.getSelectedItem().toString();
        dataForRecep_doc d = new dataForRecep_doc(id.getText(),name.getText(), add.getText(), phone.getText(), jComboBox1.getSelectedItem().toString(), age.getText(), job.getText(), jTextField7.getText(), jTextField8.getText());
        insert_doctor(d);    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField age;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField job;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables

    
}
